export const TURKEY_CITIES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce"
].sort()

export const POSITIONS = [
  "CEO / Genel Müdür",
  "CTO / Teknoloji Direktörü",
  "CFO / Finans Direktörü",
  "COO / Operasyon Direktörü",
  "Pazarlama Müdürü",
  "Satış Müdürü",
  "İnsan Kaynakları Müdürü",
  "Proje Müdürü",
  "Yazılım Geliştirici",
  "Tasarımcı",
  "Pazarlama Uzmanı",
  "Satış Temsilcisi",
  "Müşteri Hizmetleri",
  "Stajyer",
  "Diğer"
].sort()

export const COMPANY_SIZES = [
  "1-10 çalışan",
  "11-50 çalışan",
  "51-200 çalışan",
  "201-500 çalışan",
  "501-1000 çalışan",
  "1000+ çalışan"
]
